#spring.profiles.active: local
server:
  port: 80
  #ssl:
  #  enabled: true # Uses self-signed certificate because no key-store configuration is specified.

internal.lb.uri: http://34.125.111.144
spring:
  cloud:
    gateway:
      routes:
        - id: clientes
          uri: ${internal.lb.uri}:8091
          predicates:
            - Path=/api/clientes**
          filters:
            - RewritePath=/(?<path>.*), /$\{path}
        - id: planesMP
          uri: ${internal.lb.uri}:8092
          predicates:
            - Path=/api/planesMP**
          filters:
            - RewritePath=/(?<path>.*), /$\{path}
        - id: tipoIdentificacion
          uri: ${internal.lb.uri}:8092
          predicates:
            - Path=/api/tpIdentificacion**
          filters:
            - RewritePath=/(?<path>.*), /$\{path}
        - id: webapp
          uri: ${internal.lb.uri}:8090
          predicates:
            - Path=/**
          filters:
            - RewritePath=/(?<path>.*), /$\{path}